/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author VAIO
 */
public class inputdatacuca2 extends javax.swing.JFrame {

    /**
     * Creates new form inputdatacuca
     */
    public inputdatacuca2() {
        initComponents();
    }
    public Connection getConnection() {
    Connection con;
    
    try{
        con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/P3_java", "root", "");
        return con;
    }catch(SQLException e){
        return null; 
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtkota = new javax.swing.JTextField();
        txtsuhu = new javax.swing.JTextField();
        txtmaks = new javax.swing.JTextField();
        txtmin = new javax.swing.JTextField();
        txtlembap = new javax.swing.JTextField();
        txtkecangin = new javax.swing.JTextField();
        txtudara = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        tgl = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        gambar = new javax.swing.JTextField();
        ytctyt = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("INPUT DATA CUACA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 23, -1, -1));

        jLabel2.setText("Tanggal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 65, -1, -1));

        jLabel3.setText("Nama Kota");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 106, -1, -1));

        jLabel4.setText("Suhu");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 134, -1, -1));

        jLabel5.setText("Suhu Maks");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 160, -1, -1));

        jLabel6.setText("Suhu Min");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 186, -1, -1));

        jLabel7.setText("Kelembapan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 212, -1, -1));

        jLabel8.setText("Kecepatan Angin");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 238, -1, -1));

        jLabel9.setText("Tekanan Udara");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 264, -1, -1));

        jButton1.setText("Input");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 134, 67, -1));

        txtkota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkotaActionPerformed(evt);
            }
        });
        getContentPane().add(txtkota, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 103, 175, -1));
        getContentPane().add(txtsuhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 134, 175, -1));
        getContentPane().add(txtmaks, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 160, 175, -1));
        getContentPane().add(txtmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 186, 175, -1));
        getContentPane().add(txtlembap, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 212, 175, -1));
        getContentPane().add(txtkecangin, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 238, 175, -1));
        getContentPane().add(txtudara, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 264, 175, -1));

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 260, 67, -1));

        tgl.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 65, 175, -1));

        jLabel10.setText("Status");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 295, -1, -1));
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 295, 175, -1));

        jLabel11.setText("Gambar");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 334, -1, 20));
        getContentPane().add(gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 334, 175, -1));

        ytctyt.setText("Gambar");
        ytctyt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ytctytActionPerformed(evt);
            }
        });
        getContentPane().add(ytctyt, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 333, -1, -1));

        jLabel12.setText("ID");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 30, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 27, 55, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/koneksi/foto-kenapa-keindahan-senja-berbeda-beda.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, -20, 620, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            
            Connection con = getConnection();
            String query = "insert into t_cuaca (date,nama_kota,suhu,suhu_maks,suhu_min,kecepatan_angin,kelembapan,tekanan_udara,status,gambar) values (?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, ((JTextField)tgl.getDateEditor().getUiComponent()).getText());
            ps.setString(2, txtkota.getText());
            ps.setString(3, txtsuhu.getText());
            ps.setString(4, txtmaks.getText());
            ps.setString(5, txtmin.getText());
            ps.setString(6, txtkecangin.getText());
            ps.setString(7, txtlembap.getText());
            ps.setString(8, txtudara.getText());
            ps.setString(9, status.getText());
            ps.setString(10, gambar.getText());
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Berhasil Di Input");
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtkotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkotaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       try{
            
            Connection con = getConnection();
            String query = "delete from t_cuaca where ID=?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, txtkota.getText());
            
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Berhasil Dihapus");
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ytctytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ytctytActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser("C:\\Users\\VAIO\\Documents\\NetBeansProjects\\UTS\\src\\cuacagambar\\");
        jfc.showOpenDialog(null);
        File file = jfc.getSelectedFile();
        String dir = file.getName();
        gambar.setText(dir);
    }//GEN-LAST:event_ytctytActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField gambar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField status;
    private com.toedter.calendar.JDateChooser tgl;
    private javax.swing.JTextField txtkecangin;
    private javax.swing.JTextField txtkota;
    private javax.swing.JTextField txtlembap;
    private javax.swing.JTextField txtmaks;
    private javax.swing.JTextField txtmin;
    private javax.swing.JTextField txtsuhu;
    private javax.swing.JTextField txtudara;
    private javax.swing.JButton ytctyt;
    // End of variables declaration//GEN-END:variables
}
