/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts;

import javax.swing.JOptionPane;

/**
 *
 * @author VAIO
 */
public class jFomUTS extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public jFomUTS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        txtKota = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cmbhari = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        suhumaks = new javax.swing.JLabel();
        suhumin = new javax.swing.JLabel();
        kecangin = new javax.swing.JLabel();
        udara = new javax.swing.JLabel();
        kelembapan = new javax.swing.JLabel();
        hasilsuhu = new javax.swing.JLabel();
        kota = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inibesok = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jLabel1.setText("jLabel1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        setUndecorated(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Kota");

        txtKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKotaActionPerformed(evt);
            }
        });
        txtKota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKotaKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(51, 102, 255));

        cmbhari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hari ini", "Besok", " " }));
        cmbhari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbhariActionPerformed(evt);
            }
        });

        jLabel14.setText("Suhu Maksimum");

        jLabel15.setText("Suhu Minimum");

        jLabel16.setText("Kecepatan Angin");

        jLabel17.setText("Kelembapan");

        jLabel18.setText("Tekanan Udara");

        suhumaks.setText("         ");

        suhumin.setText("        ");

        kecangin.setText("     ");

        udara.setText("      ");

        kelembapan.setText("      ");

        hasilsuhu.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        hasilsuhu.setText("          ");

        kota.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kota.setText("MONITOR CUACA");

        inibesok.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inibesok.setText("         ");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cuacagambar/04n.png"))); // NOI18N
        jLabel3.setText("Broken Clouds");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(kota)
                        .addGap(62, 62, 62))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(hasilsuhu)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(269, 269, 269)
                                .addComponent(jLabel4)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inibesok, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel18))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(kelembapan, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(udara, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(kecangin))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                    .addComponent(suhumaks))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(suhumin))))
                        .addGap(7, 7, 7)))
                .addComponent(cmbhari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbhari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(inibesok, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(suhumaks))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(suhumin))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(kecangin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(kelembapan))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(udara))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hasilsuhu)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addGap(63, 63, 63))))
        );

        jMenu2.setText("File");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Input");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Data");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Help");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKotaActionPerformed

    private void cmbhariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbhariActionPerformed
        // TODO add your handling code here:
        String Hari = (String) cmbhari.getSelectedItem();
   inibesok.setText(Hari);
   if("Hari ini".equals(inibesok.getText()) && "bandung".equals(txtKota.getText())){
            hasilsuhu.setText("30 " + (char)0x00B0 + "C");
            kota.setText("Cuaca di Bandung");
            inibesok.setText("Hari ini");
            suhumaks.setText("33.0 " + (char)0x00B0 + "C");
            suhumin.setText("17.0 " + (char)0x00B0 + "C");
            kecangin.setText("20.0 m/s");
            kelembapan.setText("300.2 %");
            udara.setText("200.2 hPa");   
        }else if("Besok".equals(inibesok.getText()) && "bandung".equals(txtKota.getText())){
            hasilsuhu.setText("27 " + (char)0x00B0 + "C");
          kota.setText("Cuaca di Bandung");
         inibesok.setText("Besok");
         suhumaks.setText("28.0 " + (char)0x00B0 + "C");
            suhumin.setText("22.0 " + (char)0x00B0 + "C");
            kecangin.setText("25.0 m/s");
            kelembapan.setText("2700.4 %");
            udara.setText("200.2 hPa");   
        }else if("Hari ini".equals(inibesok.getText()) && "jakarta".equals(txtKota.getText())){
            hasilsuhu.setText("35 " + (char)0x00B0 + "C");
          kota.setText("Cuaca di Jakarta");
         inibesok.setText("Hari ini");
         suhumaks.setText("37.5 " + (char)0x00B0 + "C");
            suhumin.setText("30.0 " + (char)0x00B0 + "C");
            kecangin.setText("28.0 m/s");
            kelembapan.setText("2500.4 %");
            udara.setText("200.2 hPa");   
        }else if("Besok".equals(inibesok.getText()) && "jakarta".equals(txtKota.getText())){
            hasilsuhu.setText("32 " + (char)0x00B0 + "C");
          kota.setText("Cuaca di Jakarta");
         inibesok.setText("Besok");
         suhumaks.setText("35.5 " + (char)0x00B0 + "C");
            suhumin.setText("28.0 " + (char)0x00B0 + "C");
            kecangin.setText("25.0 m/s");
            kelembapan.setText("2400.4 %");
            udara.setText("200.2 hPa");   
        }else if("Hari ini".equals(inibesok.getText()) && "semarang".equals(txtKota.getText())){
            hasilsuhu.setText("31 " + (char)0x00B0 + "C");
          kota.setText("Cuaca di Semarang");
         inibesok.setText("Hari ini");
         suhumaks.setText("35.5 " + (char)0x00B0 + "C");
            suhumin.setText("28.0 " + (char)0x00B0 + "C");
            kecangin.setText("25.0 m/s");
            kelembapan.setText("2200.4 %");
            udara.setText("200.2 hPa");   
        }else if("Besok".equals(inibesok.getText()) && "semarang".equals(txtKota.getText())){
            hasilsuhu.setText("29 " + (char)0x00B0 + "C");
          kota.setText("Cuaca di Semarang");
         inibesok.setText("Besok");
         suhumaks.setText("30.5 " + (char)0x00B0 + "C");
            suhumin.setText("25.0 " + (char)0x00B0 + "C");
            kecangin.setText("20.0 m/s");
            kelembapan.setText("2100.4 %");
            udara.setText("200.2 hPa");   
        }else if("Hari ini".equals(inibesok.getText()) && "bekasi".equals(txtKota.getText())){
            hasilsuhu.setText("31 " + (char)0x00B0 + "C");
          kota.setText("Cuaca di Bekasi");
         inibesok.setText("Hari ini");
         suhumaks.setText("33.5 " + (char)0x00B0 + "C");
            suhumin.setText("24.0 " + (char)0x00B0 + "C");
            kecangin.setText("20.0 m/s");
            kelembapan.setText("2100.4 %");
            udara.setText("200.2 hPa");   
        }else if("Besok".equals(inibesok.getText()) && "bekasi".equals(txtKota.getText())){
            hasilsuhu.setText("29 " + (char)0x00B0 + "C");
          kota.setText("Cuaca di Bekasi");
         inibesok.setText("Besok");
         suhumaks.setText("31.5 " + (char)0x00B0 + "C");
            suhumin.setText("23.0 " + (char)0x00B0 + "C");
            kecangin.setText("20.0 m/s");
            kelembapan.setText("2100.4 %");
            udara.setText("200.2 hPa");   
        }else if("Hari ini".equals(inibesok.getText()) && "medan".equals(txtKota.getText())){
            hasilsuhu.setText("34 " + (char)0x00B0 + "C");
          kota.setText("Cuaca di Medan");
         inibesok.setText("Hari ini");
         suhumaks.setText("37.5 " + (char)0x00B0 + "C");
            suhumin.setText("27.0 " + (char)0x00B0 + "C");
            kecangin.setText("24.0 m/s");
            kelembapan.setText("2000.4 %");
            udara.setText("200.2 hPa");   
        }else if("Besok".equals(inibesok.getText()) && "medan".equals(txtKota.getText())){
            hasilsuhu.setText("32 " + (char)0x00B0 + "C");
          kota.setText("Cuaca di Medan");
         inibesok.setText("Besok");
         suhumaks.setText("30.5 " + (char)0x00B0 + "C");
            suhumin.setText("21.0 " + (char)0x00B0 + "C");
            kecangin.setText("25.0 m/s");
            kelembapan.setText("2100.4 %");
            udara.setText("220.2 hPa");   
        }
   
    }//GEN-LAST:event_cmbhariActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        hELP formhelp = new hELP ();
        formhelp.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Aplikasi monitoring cuaca"+"\n Jasmine Nurul Rizki"+"\nNIM 1641810");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtKotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKotaKeyPressed
        // TODO add your handling code here:
   String Hari = (String) cmbhari.getSelectedItem();
   inibesok.setText(Hari);
   if("Hari ini".equals(inibesok.getText()) && "bandung".equals(txtKota.getText())){
            hasilsuhu.setText("30 " + (char)0x00B0 + "C");
          kota.setText("Cuaca di Bandung");
         inibesok.setText("Hari ini");
         suhumaks.setText("33.0 " + (char)0x00B0 + "C");
            suhumin.setText("17.0 " + (char)0x00B0 + "C");
            kecangin.setText("20.0 m/s");
            kelembapan.setText("300.2 %");
            udara.setText("200.2 hPa");   
        }else if("Besok".equals(inibesok.getText()) && "bandung".equals(txtKota.getText())){
            hasilsuhu.setText("27 " + (char)0x00B0 + "C");
          kota.setText("Cuaca di Bandung");
         inibesok.setText("Besok");
         suhumaks.setText("28.0 " + (char)0x00B0 + "C");
            suhumin.setText("22.0 " + (char)0x00B0 + "C");
            kecangin.setText("25.0 m/s");
            kelembapan.setText("2700.4 %");
            udara.setText("200.2 hPa");   
        }else if("Hari ini".equals(inibesok.getText()) && "jakarta".equals(txtKota.getText())){
            hasilsuhu.setText("35 " + (char)0x00B0 + "C");
          kota.setText("Cuaca di Jakarta");
         inibesok.setText("Hari ini");
         suhumaks.setText("37.5 " + (char)0x00B0 + "C");
            suhumin.setText("30.0 " + (char)0x00B0 + "C");
            kecangin.setText("28.0 m/s");
            kelembapan.setText("2500.4 %");
            udara.setText("200.2 hPa");   
        }else if("Besok".equals(inibesok.getText()) && "jakarta".equals(txtKota.getText())){
            hasilsuhu.setText("32 " + (char)0x00B0 + "C");
          kota.setText("Cuaca di Jakarta");
         inibesok.setText("Besok");
         suhumaks.setText("35.5 " + (char)0x00B0 + "C");
            suhumin.setText("28.0 " + (char)0x00B0 + "C");
            kecangin.setText("25.0 m/s");
            kelembapan.setText("2400.4 %");
            udara.setText("200.2 hPa");   
        }else if("Hari ini".equals(inibesok.getText()) && "semarang".equals(txtKota.getText())){
            hasilsuhu.setText("31 " + (char)0x00B0 + "C");
          kota.setText("Cuaca di Semarang");
         inibesok.setText("Hari ini");
         suhumaks.setText("35.5 " + (char)0x00B0 + "C");
            suhumin.setText("28.0 " + (char)0x00B0 + "C");
            kecangin.setText("25.0 m/s");
            kelembapan.setText("2200.4 %");
            udara.setText("200.2 hPa");   
        }else if("Besok".equals(inibesok.getText()) && "semarang".equals(txtKota.getText())){
            hasilsuhu.setText("29 " + (char)0x00B0 + "C");
          kota.setText("Cuaca di Semarang");
         inibesok.setText("Besok");
         suhumaks.setText("30.5 " + (char)0x00B0 + "C");
            suhumin.setText("25.0 " + (char)0x00B0 + "C");
            kecangin.setText("20.0 m/s");
            kelembapan.setText("2100.4 %");
            udara.setText("200.2 hPa");   
        }else if("Hari ini".equals(inibesok.getText()) && "bekasi".equals(txtKota.getText())){
            hasilsuhu.setText("31 " + (char)0x00B0 + "C");
          kota.setText("Cuaca di Bekasi");
         inibesok.setText("Hari ini");
         suhumaks.setText("33.5 " + (char)0x00B0 + "C");
            suhumin.setText("24.0 " + (char)0x00B0 + "C");
            kecangin.setText("20.0 m/s");
            kelembapan.setText("2100.4 %");
            udara.setText("200.2 hPa");   
        }else if("Besok".equals(inibesok.getText()) && "bekasi".equals(txtKota.getText())){
            hasilsuhu.setText("29 " + (char)0x00B0 + "C");
          kota.setText("Cuaca di Bekasi");
         inibesok.setText("Besok");
         suhumaks.setText("31.5 " + (char)0x00B0 + "C");
            suhumin.setText("23.0 " + (char)0x00B0 + "C");
            kecangin.setText("20.0 m/s");
            kelembapan.setText("2100.4 %");
            udara.setText("200.2 hPa");   
        }else if("Hari ini".equals(inibesok.getText()) && "medan".equals(txtKota.getText())){
            hasilsuhu.setText("34 " + (char)0x00B0 + "C");
          kota.setText("Cuaca di Medan");
         inibesok.setText("Hari ini");
         suhumaks.setText("37.5 " + (char)0x00B0 + "C");
            suhumin.setText("27.0 " + (char)0x00B0 + "C");
            kecangin.setText("24.0 m/s");
            kelembapan.setText("2000.4 %");
            udara.setText("200.2 hPa");   
        }else if("Besok".equals(inibesok.getText()) && "medan".equals(txtKota.getText())){
            hasilsuhu.setText("32 " + (char)0x00B0 + "C");
          kota.setText("Cuaca di Medan");
         inibesok.setText("Besok");
         suhumaks.setText("30.5 " + (char)0x00B0 + "C");
            suhumin.setText("21.0 " + (char)0x00B0 + "C");
            kecangin.setText("25.0 m/s");
            kelembapan.setText("2100.4 %");
            udara.setText("220.2 hPa");   
        }
    }//GEN-LAST:event_txtKotaKeyPressed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        inputdatacuca jj = new inputdatacuca();
        jj.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        FrmData kk = new FrmData();
        kk.setVisible(true);
    }//GEN-LAST:event_jMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbhari;
    private javax.swing.JLabel hasilsuhu;
    private javax.swing.JLabel inibesok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kecangin;
    private javax.swing.JLabel kelembapan;
    private javax.swing.JLabel kota;
    private javax.swing.JLabel suhumaks;
    private javax.swing.JLabel suhumin;
    private javax.swing.JTextField txtKota;
    private javax.swing.JLabel udara;
    // End of variables declaration//GEN-END:variables
}
